name: Test and Deploy
on: workflow_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Deployed"